apiVersion: apps/v1
kind: Deployment
metadata:
  name: optima-manage-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optima-manage-grafana
  template:
    metadata:
      labels:
        app: optima-manage-grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
---
apiVersion: v1
kind: Service
metadata:
  name: optima-manage-grafana
spec:
  selector:
    app: optima-manage-grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
  type: LoadBalancer