apiVersion: v1
kind: ConfigMap
metadata:
  name: optima-manage-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'backend'
        static_configs:
          - targets: ['optima-manage-backend:3000']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optima-manage-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optima-manage-prometheus
  template:
    metadata:
      labels:
        app: optima-manage-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: config
          configMap:
            name: optima-manage-prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: optima-manage-prometheus
spec:
  selector:
    app: optima-manage-prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: http
  type: LoadBalancer